//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace автомастерская
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class car_dealershipEntities1 : DbContext
    {
        public static car_dealershipEntities1 _context;

        public car_dealershipEntities1()
            : base("name=car_dealershipEntities1")
        {
        }

        public static car_dealershipEntities1 GetContext()
        {
            if (_context == null)
                _context = new car_dealershipEntities1();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Male> Male { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<staffes> staffes { get; set; }


    }
}
